Apptrack 1010 b (jk)
CBIIT/app-tracker pull request #307
Opened 2024-04-01 20:20 UTC by jaykurani

2024-04-05 16:57 UTC, HarvBCoding requested changes

2024-04-05 16:57 UTC, HarvBCoding commented on src/containers/CreateVacancy/Forms/BasicInfo/BasicInfo.js
Changes to this file are not necessary as committee members do not have access to this page

2024-04-05 16:57 UTC, HarvBCoding commented on src/containers/CreateVacancy/EditVacancy.js
Changes to this file are not necessary as committee members do not have access to this page

2024-04-05 16:57 UTC, HarvBCoding commented on src/containers/CreateVacancy/CreateVacancy.js
Changes to this file are not necessary as committee members do not have access to this page

2024-04-05 16:57 UTC, HarvBCoding commented on webpack/servicenow.config.js
Please delete user information from repo

2024-04-09 19:01 UTC, closed without merging

2024-04-09 19:02 UTC, jaykurani commented
Completed with another branch